set(ORDBK_SANITIZER "OFF" CACHE STRING "Sanitizer: OFF, ASAN, UBSAN, TSAN, ASAN_UBSAN")
set_property(CACHE ORDBK_SANITIZER PROPERTY STRINGS OFF ASAN UBSAN TSAN ASAN_UBSAN)

function(ordbk_apply_sanitizers target)
    if(ORDBK_SANITIZER STREQUAL "OFF")
        return()
    endif()
    if(MSVC)
        if(ORDBK_SANITIZER MATCHES "ASAN")
            target_compile_options(${target} PRIVATE /fsanitize=address)
        endif()
        return()
    endif()
    set(flags "")
    if(ORDBK_SANITIZER STREQUAL "ASAN" OR ORDBK_SANITIZER STREQUAL "ASAN_UBSAN")
        list(APPEND flags -fsanitize=address -fno-omit-frame-pointer)
    endif()
    if(ORDBK_SANITIZER STREQUAL "UBSAN" OR ORDBK_SANITIZER STREQUAL "ASAN_UBSAN")
        list(APPEND flags -fsanitize=undefined)
    endif()
    if(ORDBK_SANITIZER STREQUAL "TSAN")
        list(APPEND flags -fsanitize=thread -fno-omit-frame-pointer)
    endif()
    target_compile_options(${target} PRIVATE ${flags} -g -O1)
    target_link_options(${target} PRIVATE ${flags})
endfunction()
